### PR TITLE
Dataset saver

### PR DESCRIPTION
**Pull request by gmrukwa**
Rebased clone of https://github.com/spectre-team/spectre/pull/146. To be accepted if nothing really breaks.

### CODE REVIEW

**Comment by gmrukwa** [comment]
[Dataset store](https://trello.com/c/eak9PgmB/144-dataset-store)

**Comment by gmrukwa** [comment]
[Prepare simple saver of the datasets](https://trello.com/c/OkSHuM5h/259-prepare-simple-saver-of-the-datasets)

**Review by Daroslaw — APPROVED** [review]
Seems to be ok.

**Comment by gmrukwa** [comment]
Closing, as this has already been approved in source repository.

**Pull request merged**
